#!/bin/bash

value_bets=$1

prep_statement() {
  IFS=$'\n'
  for value_bet in $value_bets;do
    bet_type=$(echo "${value_bet}" | cut -d ',' -f 1 |tr -d '"')
    event_id=$(echo "${value_bet}" | cut -d ',' -f 2|tr -d '"')
    book=$(echo "${value_bet}" | cut -d ',' -f 3 |tr -d '"')
    bet_option=$(echo "${value_bet}" | cut -d ',' -f 4 |tr -d '"')
    price=$(echo "${value_bet}" | cut -d ',' -f 5 |tr -d '"')
    points=$(echo "${value_bet}" | cut -d ',' -f 6 |tr -d '"')
    edge=$(echo "${value_bet}" | cut -d ',' -f 7)
    sport_radar_id=$(echo "${value_bet}" | cut -d ',' -f 8|tr -d '"')
    echo "('${bet_type}', '${event_id}', '${book}', '${bet_option}', ${price}, ${points}, ${edge}, ${sport_radar_id}), "
  done
}

if [ -n "$value_bets" ]; then
  # example: "1X2",12345,"betfirst","1",2.34,0,0.0489
  export SNOWSQL_ACCOUNT=bs92548.europe-west4.gcp
  export SNOWSQL_USER=demuinckpieterjan
  export SNOWSQL_PWD=$(gcloud secrets versions access latest --secret="snowflake_pass")
  export SNOWSQL_ROLE=SYSADMIN
  export SNOWSQL_DATABASE=PROTRADER
  export SNOWSQL_WAREHOUSE=COMPUTE_WH
  export SNOWSQL_SCHEMA=VALUE_BETS


  values=$(prep_statement)

  modified=$(echo ${values} |rev | cut -c2- |rev)

  echo "${modified}"

  snowsql -q "insert into value_bets(bet_type, event_id, book, bet_option, price, points, edge, sport_radar_id) values ${modified}"

fi


