#!/bin/bash

curl --request POST \
  --url https://oddsservice.cashpoint.com/odds/getGames/8 \
  --header 'Content-Type: application/json' \
  --header 'x-brand: 7' \
  --header 'x-client-country: 21' \
  --header 'x-language: 2' \
  --header 'x-location: 21' \
  --data '{"leagueIds":[6898], "sportId":1,"gameTypes":[1, 4],"limit":20000,"jurisdictionId":30}'