#!/bin/bash

get_events() {
  local events=$(curl -s 'https://eu-offering.kambicdn.org/offering/v2018/ubbe/event/group/'"${1}"'.json?includeParticipants=false')
  event_ids=$(echo "${events}" | jq '.events[] | select(.tags[] == "MATCH") | .id')
  local output=[
  for id in ${event_ids}; do
    local test=$(get_sport_radar_id "${id}" | awk '{if($1 != "nul") { print $1 } else {print 0}}')
    output+='{"kambi_id":'"${id}"',"sport_radar_id":'"${test}"'},'
  done
  echo "${output%?}"] | jq .
}

get_sport_radar_id() {
  local sportradar_match=$(curl -s 'https://nl.unibet.be/kambi-rest-api/sportradar/widget/event/nl/'"${1}")
  local sportradar_widget_url=$(echo "${sportradar_match}" | jq '.content | .[0].Resource')
  IFS='matchId='
  read -ra ADDR <<<"$sportradar_widget_url"
  match_id="${ADDR[*]: -1}"
  echo "${match_id%?}"
}

get_events $1
