#!/bin/bash

get_events() {
  local url=$1
  local league=$2
  local book='"meridian"'
  curl -s "${url}" | jq --raw-output '.[0].events[] | [.id, .betradarUnified["id"]] | @csv' | awk -v league="${league}" -v book="${book}" -F"," 'BEGIN { OFS = "," } {$3=book;$4=league; print}' >> "${league}"_league_events.csv
}

get_events https://meridianbet.be/sails/sport/58/region/26/league/first-division-a '"jupiler_pro_league"' &
get_events https://meridianbet.be/sails/sport/58/region/4/league/serie-a '"serie_a"' &
get_events https://meridianbet.be/sails/sport/58/region/1/league/premier-league '"premier_league"' & 
get_events https://meridianbet.be/sails/sport/58/region/2/league/bundesliga '"bundesliga"' &
get_events https://meridianbet.be/sails/sport/58/region/3/league/la-liga '"la_liga"' &
get_events https://meridianbet.be/sails/sport/58/region/5/league/ligue-1 '"ligue_1"' 

wait
echo event_id,sportradar_id,book,league > meridian_events.csv

cat *_league_events.csv >> meridian_events.csv
rm *_league_events.csv
