apiVersion: v1
kind: Service
metadata:
    name: kambi-worker
    labels:
        app: kambi
        tier: backend
        role: worker
spec:
    ports:
    - port: 3000
      targetPort: 3000
    selector:
        app: kambi
        tier: backend
        role: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kambi-worker
spec:
    selector:
        matchLabels:
            app: kambi
            role: worker
            tier: backend
    replicas: 1
    template:
        metadata:
            labels:
                app: kambi
                role: worker
                tier: backend
        spec:
            containers:
                - name: worker
                  image: trademate.azurecr.io/kambi:3
                  ports:
                  - containerPort: 3000  