#!/bin/bash

source websocket
source sportradar
source transformations

readonly SBTECH_SITE_IDS=$(cat ./resources/sbtech_site_ids.json)

#######################################
# Returns cashpoint sport events for given league id
# Globals:
#   None
# Arguments:
#   league
# Outputs:
#   csv lines containing event id and sport radar id
#######################################
cashpoint_provider_events() {
  local league_id=$1
  local host=$2
  curl -s 'https://'"${host}"'/odds/getGames/8' \
  -H 'x-language: 2' \
  -H 'x-brand: 7' \
  --data-raw '{"leagueIds":['"${league_id}"'],"gameTypes":[7],"jurisdictionId":30}' \
  | jq --raw-output '.games[] | [.id, .statisticsId]
  | @csv'
}

#######################################
# BETCENTER
#######################################

betcenter_events() {
  local league_id=$1
  cashpoint_provider_events "${league_id}" oddsservice.betcenter.be
}

betcenter_betoffers() {
  event_id=$1

  curl -s 'https://oddsservice.betcenter.be/odds/getGames/8' \
    -H 'x-language: 2' \
    -H 'x-brand: 7' \
    --data-raw '{"gameIds":['"${event_id}"'],"gameTypes":[1,4,5],"jurisdictionId":30}' \
    | jq --raw-output '.games[]
    | .id as $eventId
    | .markets[]
    | .id as $betType
    | .anchor as $points
    | .tips[]
    | [$betType, $eventId, "betcenter", .text, .odds / 100, $points // 0] | @csv' \
    | sed 's/22242/1X2/g; s/22462/OVER_UNDER/g; s/22252/OVER_UNDER/g; s/22482/OVER_UNDER/g; s/22492/OVER_UNDER/g; s/22502/OVER_UNDER/g; s/22512/OVER_UNDER/g; s/22472/OVER_UNDER/g' \
    | sed 's/"0-1"/"Under"/g; s/"2+"/"Over"/g; s/"0-2"/"Under"/g; s/"0-3"/"Under"/g; s/"0-4"/"Under"/g; s/"0-5"/"Under"/g; s/"0-6"/"Under"/g; s/"1+"/"Over"/g; s/"2+"/"Over"/g; s/"3+"/"Over"/g; s/"4+"/"Over"/g; s/"5+"/"Over"/g; s/"6+"/"Over"/g; s/"7+"/"Over"/g; s/"0"/"Under"/g' \
    | grep '1X2\|OVER_UNDER'
}

#######################################
# BWIN
#######################################

bwin_events() {
  local league_id=$1
  local book='"bwin"'

  curl -G -s 'https://cds-api.bwin.be/bettingoffer/fixtures' \
  -d x-bwin-accessid=NTE3MjUyZDUtNGU5Ni00MTkwLWJkMGQtMDhmOGViNGNiNmRk \
  -d lang=en \
  -d country=BE \
  -d userCountry=BE \
  -d fixtureTypes=Standard \
  -d state=Latest \
  -d offerMapping=Filtered \
  -d offerCategories=Gridable \
  -d fixtureCategories=Gridable \
  -d competitionIds="${league_id}" \
  -d skip=0 \
  -d take=100 \
  -d sortBy=Tags \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36' \
  | jq --raw-output '.fixtures[] | [.id, .addons.liveMatchTracker.sportradarId // .addons.betRadar] | @csv'
}

bwin_betoffers() {
  event_id=$1

  curl 'https://cds-api.bwin.be/bettingoffer/fixture-view?x-bwin-accessid=NTE3MjUyZDUtNGU5Ni00MTkwLWJkMGQtMDhmOGViNGNiNmRk&lang=nl&country=BE&userCountry=BE&offerMapping=All&fixtureIds='"${event_id}"'&state=Latest&includePrecreatedBetBuilder=false&supportVirtual=false' \
    -H 'authority: cds-api.bwin.be' \
    -H 'accept: application/json, text/plain, */*' \
    -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36' \
    | jq --raw-output '.fixture
    | .id as $event_id
    | .optionMarkets[] // .games[]
    | .name.value as $betType
    | .options[] // .results[]
    | .attr as $points
    | .sourceName.value as $option1
    | .name.value as $option2
    | [$betType, $event_id, "bwin", $option1 // $option2, .price.odds, $points // .name.value // 0]
    | @csv' \
    | grep '"Resultaat"\|"Aantal doelpunten"' \
    | sed 's/"Resultaat"/"1X2"/g; s/"Aantal doelpunten"/"OVER_UNDER"/g;'
}


#######################################
# SBTECH
#######################################
sbtech_token() {
  local book=$1
  site_id=$(echo "${SBTECH_SITE_IDS}" | jq '.["'"${book}"'"]')
  token_message=$(curl -s 'https://sbapi.sbtech.com/'"${book}"'/auth/platform/v1/api/GetTokenBySiteId/'"${site_id}")
  IFS=' = '
  read -a strarr <<<"${token_message}"
  token_raw="${strarr[1]}"
  token_temp=${token_raw%\'}
  echo "${token_temp#\'}"
}

sbtech_events() {
  local league_id=$1
  local token=$2
  local book=betfirst

  if [ -z "${token}" ]
  then
    token=$(sbtech_token "${book}")
  fi

  curl -s 'https://sbapi.sbtech.com/'"${book}"'/sportsdata/v2/events?query=$filter=leagueId%20eq%20%27'"${league_id}"'%27&locale=en' \
  -H 'accept: application/json, text/javascript, */*; q=0.01' \
  -H 'authorization: Bearer '"${token}" \
  -H 'content-type: application/json-patch+json' \
  --compressed \
  | jq --raw-output '.data.events[]
  | .id as $id
  | .media[]
  | select(.providerName == "BetRadarV3")
  | [$id, .providerEventId]
  | @csv' \
  | sort -u
}

sbtech_betoffers() {
  local event_id=$1
  local book=$2
  local token=$3

  if [ -z "${token}" ]
  then
    token=$(sbtech_token "${book}")
  fi

    curl -s 'https://sbapi.sbtech.com/'"${book}"'/sportsdata/v2/events?query=$filter=id%20eq%20%27'"${event_id}"'%27&includeMarkets=$filter=' \
  -H 'authority: sbapi.sbtech.com' \
  -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
  -H 'accept: application/json, text/javascript, */*; q=0.01' \
  -H 'locale: en' \
  -H 'authorization: Bearer '"${token}" \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36' \
  -H 'content-type: application/json-patch+json' \
  -H 'origin: https://betfirst.dhnet.be' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://betfirst.dhnet.be/' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed \
  | jq --raw-output '.data.markets[]
  | .marketType.id as $type_id
  | .eventId as $event_id
  | (.selections[]
  | [$type_id, $event_id, '\""${book}"\"', .outcomeType, (.displayOdds.decimal | tonumber), .points // 0]
  | @csv )' \
  | sed 's/"1_0"/"1X2"/g; s/"1_1"/"1X2_H1"/g; s/"1_2"/"1X2_H2"/g; s/"3_200"/"OVER_UNDER"/g; s/"Home"/"1"/g; s/"Away"/"2"/g; s/"Tie"/"X"/g' \
  | grep '"1X2"\|"OVER_UNDER"'
}

#######################################
# BINGOAL
#######################################
init_bingoal() {
    curl -s 'https://www.bingoal.be/nl/Sport#/detail/'"${event_id}" --header "accept-encoding: application/json" -D bingoal_headers > bingoal_response
}

get_bingoal_cookies() {
  cookie_raw=$(grep -m 2 'SET-COOKIE: ' bingoal_headers | cut -c 12-)
  rm bingoal_headers
  echo "${cookie_raw//[$'\t\r\n']}"
}

get_bingoal_k_parameter(){
  k=$(cat bingoal_response | grep '_k = ' | cut -d\' -f 2)
  rm bingoal_response
  echo "${k}"
}

bingoal_events() {
  league_id=$1
  init_bingoal
  cookie=$(get_bingoal_cookies)
  k=$(get_bingoal_k_parameter)

  curl -s 'https://www.bingoal.be/A/sport' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'Cookie: '"${cookie}" \
  --data-raw 'func=sport&action=SOCCER&id='"${league_id}"'&k='"${k}" \
  | jq --raw-output '.sports[].matches[] | [.ID, .betradarID] | @csv'
}

bingoal_betoffers() {
  event_id=$1
  init_bingoal
  cookie=$(get_bingoal_cookies)
  k=$(get_bingoal_k_parameter)

  curl -s 'https://www.bingoal.be/A/sport' \
  -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'Cookie: '"${cookie}" \
  --data-raw 'func=detail&action=SOCCER&id='"${event_id}"'&b=1&k='"${k}" \
  | jq --raw-output '.box[0].match
  | .ID as $eventId
  | .categories[].subbets[]
  | .name as $betType
  | .tips[]
  | [$betType, $eventId, "bingoal", .shortName, (.odd | tonumber), .sov]
  | @csv' \
  | sed 's/Totaal aantal doelpunten/OVER_UNDER/g; s/U [0-9].[0-9]/Under/g; s/O [0-9].[0-9]/Over/g; s/,""/,"0"/g' \
  | grep '"1X2"\|"OVER_UNDER"' \
  | sort -u
}

#######################################
# BETCONSTRUCT: CIRCUS, GOLDEN_VEGAS
#######################################

betconstruct_login() {
  login_message=$1
  port=$2
  login_success=false

  while [ "${login_success}" != true ]
  do
    send_message "${login_message}" "${port}"
    message=$(get_message "${port}")
    login_success=$(echo "${message}" | jq --raw-output '.Message|fromjson|.Success')
  done
}

circus_login() {
  port=$1
  login_message='{"Id":"8d717d3e-0174-c289-c818-ab8463a98708","TTL":10,"MessageType":1,"Message":"{\"NodeType\":1,\"Identity\":\"f56e40a4-237d-4be4-997e-ffb4adad4ffe\",\"EncryptionKey\":\"\",\"ClientInformations\":{\"AppName\":\"Front;Registration-Origin: default\",\"ClientType\":\"Responsive\",\"Version\":\"1.0.0\",\"UserAgent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36\",\"LanguageCode\":\"nl\",\"RoomDomainName\":\"CIRCUS\"},\"SupportedCompressions\":\"LZS2\"}"}'
  betconstruct_login "${login_message}" "${port}"
}

golden_vegas_login() {
  port=$1
  login_message='{"Id":"73a8944c-8b4e-2d5b-6781-957e8c1945ac","TTL":10,"MessageType":1,"Message":"{\"NodeType\":1,\"Identity\":\"4f92eaff-b795-46a7-8070-42035e5ec551\",\"EncryptionKey\":\"\",\"ClientInformations\":{\"AppName\":\"Front;Registration-Origin: default\",\"ClientType\":\"Responsive\",\"Version\":\"1.0.0\",\"UserAgent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36\",\"LanguageCode\":\"nl\",\"RoomDomainName\":\"GOLDENVEGAS\"}}"}'
  betconstruct_login "${login_message}" "${port}"
}

betconstruct_events() {
  league_id=$1
  compressed=$2
  events_parsed=null

  while [ "${events_parsed}" == null ]
  do
    events_message='{"Id":"49b9e428-925c-4b45-0149-b17b3985c6ab","TTL":10,"MessageType":1000,"Message":"{\"Direction\":1,\"Id\":\"6907a9a1-28ea-c6b5-6d54-caa981a70599\",\"Requests\":[{\"Id\":\"c6ce7092-ad23-b92d-dafb-8d029cb63024\",\"Type\":201,\"Identifier\":\"GetLeaguesDataSourceFromCache\",\"AuthRequired\":false,\"Content\":\"{\\\"Entity\\\":{\\\"Language\\\":\\\"en\\\",\\\"BettingActivity\\\":0,\\\"PageNumber\\\":0,\\\"OnlyShowcaseMarket\\\":true,\\\"IncludeSportList\\\":true,\\\"EventSkip\\\":0,\\\"EventTake\\\":500,\\\"EventType\\\":0,\\\"SportId\\\":844,\\\"RequestString\\\":\\\"LeagueIds='"${league_id}"'&OnlyMarketGroup=Main\\\"}}\"}],\"Groups\":[]}"}'
    send_message "${events_message}" "${port}"
    response=$(get_message "${port}" | jq --raw-output '.Message|fromjson|.Requests[0].Content')
    if [ "${compressed}" == true ]
    then
      events_parsed=$(node ./lzstring_parser "${response}")
    else
      events_parsed=$(echo "${response}")
    fi
  done

  echo "${events_parsed}" | jq --raw-output '.LeagueDataSource.LeagueItems[].EventItems[]
  | [.EventId, (.UrlBetStats | split("/")[6])] | @csv'
}

circus_events() {
  league_id=$1
  host=wss://wss01.circus.be
  port=8712

  create_connection "${host}" "${port}"
  ws_pid=$!
  circus_login "${port}"
  betconstruct_events "${league_id}" true
  kill -9 "${ws_pid}"
}

golden_vegas_events() {
  league_id=$1
  host=wss://wss.goldenvegas.be
  port=8734

  create_connection "${host}" "${port}"
  ws_pid=$!
  golden_vegas_login "${port}"
  betconstruct_events "${league_id}" false
  kill -9 "${ws_pid}"
}

betconstruct_betoffers() {
  event_id=$1
  book=$2
  compressed=$3
  betoffers_parsed=null

  while [ "${betoffers_parsed}" == null ]
  do

    betoffers_message='{"Id":"0c503c67-1d84-457f-7da1-cc6d77ace742","TTL":10,"MessageType":1000,"Message":"{\"Direction\":1,\"Id\":\"b67f908a-0d89-8c65-244c-bf4b3d5fa8dc\",\"Requests\":[{\"Id\":\"3f9689ba-8ea5-a7a4-3cab-49c26ca63fb3\",\"Type\":201,\"Identifier\":\"GetLeaguesDataSourceFromCache\",\"AuthRequired\":false,\"Content\":\"{\\\"Entity\\\":{\\\"Language\\\":\\\"en\\\",\\\"BettingActivity\\\":0,\\\"PageNumber\\\":0,\\\"IncludeSportList\\\":false,\\\"EventType\\\":0,\\\"SportId\\\":844,\\\"RegionId\\\":0,\\\"EventId\\\":'"${event_id}"',\\\"RequestString\\\":\\\"OnlyMarketGroup=Main\\\"}}\"}],\"Groups\":[]}"}'
    send_message "${betoffers_message}" "${port}"
    response=$(get_message "${port}" | jq --raw-output '.Message|fromjson|.Requests[0].Content')
    if [ "${compressed}" == true ]
    then
      betoffers_parsed=$(node ./lzstring_parser "${response}")
    else
      betoffers_parsed=$(echo "${response}")
    fi
  done

  echo "${betoffers_parsed}" | jq --arg book "${book}" --raw-output '.LeagueDataSource.LeagueItems[].EventItems[]
  | .EventId as $eventId
  | .Team1Name as $homeTeam
  | .Team2Name as $awayTeam
  | .MarketItems[]
  | .BetType as $betType
  | .OutcomeItems[]
  | [$betType, $eventId, $book, if .Name == $homeTeam then "1" elif .Name == $awayTeam then "2" else "X" end, .Odd, 0]
  | @csv' \
  | sed 's/"P1XP2"/"1X2"/g;' \
  | grep '"1X2"'
}

circus_betoffers() {
  event_id=$1
  port=8541

  create_connection wss://wss01.circus.be "${port}"
  circus_ws_pid=$!

  circus_login "${port}"

  betconstruct_betoffers "${event_id}" circus true

  kill -9 "${circus_ws_pid}"
}

golden_vegas_betoffers() {
  event_id=$1
  port=8534

  create_connection wss://wss.goldenvegas.be "${port}"
  ws_pid=$!

  golden_vegas_login "${port}"

  betconstruct_betoffers "${event_id}" golden_vegas false

  kill -9 "${ws_pid}"
}

#######################################
# BETCONSTRUCT APPS: STAR CASINO
#######################################

starcasino_login() {
  port=$1

  rid=$(date +%s)
  login_message='{"command":"request_session","params":{"language":"eng","site_id":"385","release_date":"15/09/2020-16:48"},"rid":"'"${rid}"'"}' \

  login_success=false

  while [ "${login_success}" != true ]
  do
    send_message "${login_message}" "${port}"
    message=$(get_message "${port}")
    login_success=$(echo "${message}" | jq --raw-output 'if .code == 0 then "true" else "false" end')
  done
}

get_participant_id() {
  name=$1
  participants=$2
  jq_string='.['"${name}"']'
  participant=$(echo "${participants}" | jq "${jq_string}")
  echo "${participant}"
}

starcasino_events() {
  league_id=$1
  port=8711

  sport_radar_matches=$(event_full_feed | grep Soccer)

  create_connection wss://eu-swarm-ws-re.bcapps.net "${port}"
  ws_pid=$!

  starcasino_login "${port}"

  rid=$(date +%s)
  jq_string='.["'"${league_id}"'"]'
  league_participants=$(cat < ./resources/bcaps_sportradar_participant.json | jq "${jq_string}")

  events_parsed=null

  while [ "${events_parsed}" == null ]
  do
    events_message='{"command":"get","params":{"source":"betting","what":{"game":["id", "team1_name", "team1_id", "team2_name", "team2_id"]},"where":{"competition":{"id":'"${league_id}"'}},"subscribe":true},"rid":"'"${rid}"'"}'
    send_message "${events_message}" "${port}"
    events_parsed=$(get_message "${port}" | jq --raw-output '.data.data.game | values[] | [.id, .team1_name, .team2_name] | @csv')
  done

  IFS=$'\n'
    for event in ${events_parsed}
    do
      event_id=$(echo "${event}" | cut -d',' -f 1)
      home_team=$(echo "${event}" | cut -d',' -f 2 | tr -d '"' | awk '{$1=$1};1')
      away_team=$(echo "${event}" | cut -d',' -f 3 | tr -d '"' | awk '{$1=$1};1')
      home_sportradar_team_id=$(get_participant_id \"${home_team}\" "${league_participants}")
      away_sportradar_team_id=$(get_participant_id \"${away_team}\" "${league_participants}")
      sportradar_id=$(echo "${sport_radar_matches}" | grep ''"${home_sportradar_team_id}"'' | grep ''"${away_sportradar_team_id}"'' | cut -d',' -f 3)
      if [ -n "${sportradar_id}" ]
      then
      echo "${event_id}","${sportradar_id}"
      fi
  done

  kill -9 "${ws_pid}"

}

starcasino_betoffers() {
  event_id=$1
  port=8531

  create_connection wss://eu-swarm-ws-re.bcapps.net "${port}"
  ws_pid=$!

  starcasino_login "${port}"

  rid=$(date +%s)

  echo '{"command":"get","params":{"source":"betting","what":{"game":["id","show_type","markets_count","start_ts","is_live","is_blocked","is_neutral_venue","team1_id","team2_id","game_number","text_info","is_stat_available","type","info","team1_name","team2_name","tv_info","stats","add_info_name"],"market":["id","col_count","type","name_template","sequence","point_sequence","express_id","cashout","display_key","display_sub_key","group_id","name","group_name","order","extra_info","group_order"],"event":["order","id","type_1","type","type_id","original_order","name","price","nonrunner","ew_allowed","sp_enabled","extra_info","base","home_value","away_value","display_column"]},"where":{"game":{"id":'"${event_id}"'}},"subscribe":false},"rid":'"${rid}"'}' \
  | nc 127.0.0.1 "${port}"

  get_message "${port}" \
   | jq --raw-output '.data.data.game["'"${event_id}"'"] | .id as $eventId | .market
  | to_entries
  | .[]
  | .value
  | .type as $betType
  | .event
  | to_entries
  | .[]
  | .value
  | [$betType, $eventId, "starcasino", .type, .price, .base]
  | @csv' \
  | sed 's/"OverUnder"/"OVER_UNDER"/g; s/"P1XP2"/"1X2"/g; s/"P1"/"1"/g; s/"P2"/"2"/g; ' \
  | grep '"1X2"\|"OVER_UNDER"'


  kill -9 "${ws_pid}"
}

#######################################
# goldenpalace
#######################################

goldenpalace_events() {
  league_id=$1
  book='goldenpalace'
  curl -G -s 'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents' \
  -d timezoneOffset=-120 \
  -d langId=8 \
  -d skinName="${book}" \
  -d configId=19 \
  -d culture=en-gb \
  -d countryCode=BE \
  -d deviceType=Desktop \
  -d numformat=en \
  -d integration="${book}" \
  -d sportids=0 \
  -d categoryids=0 \
  -d champids="${league_id}" \
  -d group=AllEvents \
  -d period=periodall \
  -d withLive=false \
  -d outrightDisplay=none \
  -d couponType=0 \
  -d startDate=2021-06-16T12%3A21%3A00.000Z \
  -d endDate=2030-06-23T12%3A21%3A00.000Z \
  | jq --raw-output '.Result.Items[0].Events | map(.ExtId |= split(":"))[] | [.Id, .ExtId[2]] | @csv'
}

goldenpalace_betoffers() {
  event_id=$1

  curl -s 'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEventDetails?timezoneOffset=-120&langId=8&skinName=goldenpalace&configId=19&culture=en-gb&countryCode=BE&deviceType=Desktop&numformat=en&integration=goldenpalace&eventId='"${event_id}"'&sportId=66' \
    | jq --raw-output '.Result.MarketGroups[]
    | select(.Name == "Main")
    | .Items[]
    | .Name as $betType
    | .SpecialOddsValue as $points
    | .Id as $eventId
    | .Items[]
    | [$betType, $eventId, "golden_palace", .Name, (.Price | tonumber), .SPOV]
    | @csv' \
    | sed 's/"1x2"/"1X2"/g; s/"Total"/"OVER_UNDER"/g; s/"Over [0-9].[0-9][0-9]"/"Over"/g; s/"Over [0-9].[0-9]"/"Over"/g; s/"Over [0-9]"/"Over"/g' \
    | sed 's/"Under [0-9].[0-9][0-9]"/"Under"/g; s/"Under [0-9].[0-9]"/"Under"/g; s/"Under [0-9]"/"Under"/g'\
    | sed 's/"Draw"/"X"/g; s/,""/,"0"/g' \
    | grep '"1X2"\|"OVER_UNDER"'
}

#######################################
# ladbrokes
#######################################

ladbrokes_events() {
    league=$1
    curl -s 'https://www.ladbrokes.be/detail-service/sport-schedule/services/meeting/calcio/'"${league}"'?prematch=1&live=0' \
    --header 'x-eb-accept-language: en_BE' \
    --header 'x-eb-marketid: 5' \
    --header 'x-eb-platformid: 2' \
    | jq --raw-output --arg league "${league}" '.result.dataGroupList[].itemList[].eventInfo | [($league + "/" + .aliasUrl), .programBetradarInfo.matchId] | @csv'
}

ladbrokes_betoffers() {
  event_id=$1

  curl -s 'https://www.ladbrokes.be/detail-service/sport-schedule/services/event/calcio/'"${event_id}"'?prematch=1&live=0' \
    -H 'x-eb-accept-language: nl_BE' \
    -H 'accept: application/json, text/plain, */*' \
    -H 'x-eb-marketid: 5' \
    -H 'x-eb-platformid: 2' \
    | jq --raw-output '.result
    | .eventInfo.aliasUrl as $eventId
    | .betGroupList[].oddGroupList[]
    | .betId as $betType
    | .oddList[]
    | [$betType, $eventId, "ladbrokes", .oddDescription, .oddValue /100, .additionalInfo[0] / 100]
    | @csv' \
    | grep '24,\|1907' \
    | sed 's/24,/"1X2",/g; s/1907,/"OVER_UNDER",/g' \
    | sed 's/"Meer"/"Over"/g; s/"Minder"/"Under"/g' \
    | grep '"1X2"\|"OVER_UNDER"'
}

#######################################
# meridian
#######################################

meridian_events() {
  url=$1
  curl -s "${url}" | jq --raw-output '.[0].events[] | [.id, .betradarUnified["id"]] | @csv'
}

meridian_betoffers() {
  event_id=$1

  curl 'https://meridianbet.be/sails/events/'"${event_id}" \
  | jq --raw-output '.market[]
  | .templateId as $betType
  | .id as $eventId
  | .overUnder as $points
  | .selection[]
  | [$betType, $eventId, "meridian", .name, (.price | tonumber), $points // 0]
  | @csv' \
  | sed ' s/[][]//g; s/Rival2/2/g; s/Rival1/1/g; s/draw/X/g; s/under/Under/g; s/over/Over/g' \
  | sed 's/"3999"/"1X2"/g; s/"4004"/"OVER_UNDER"/g' \
  | grep '"1X2"\|"OVER_UNDER"'
}

#######################################
# pinnacle
#######################################

get_pinnacle_participant_id() {
  name=$1
  participants=$2
  jq_string='.['"${name}"']'
  participant=$(echo "${participants}" | jq "${jq_string}")
  echo "${participant}"
}

pinnacle_events() {
  league_id=$1
  sport_radar_matches=$(event_full_feed | grep Soccer)

  jq_string='.["'"${league_id}"'"]'
  league_participants=$(cat < ./resources/pinnacle_sportradar_participant.json | jq "${jq_string}")
  events=$(curl -s 'https://guest.api.arcadia.pinnacle.com/0.1/leagues/'"${league_id}"'/matchups' \
  -H 'authority: guest.api.arcadia.pinnacle.com' \
  -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
  -H 'accept: application/json' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36' \
  -H 'x-api-key: CmX2KcMrXuFmNg6YFbmTxE0y9CIrOi0R' \
  -H 'content-type: application/json' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed \
  | jq --raw-output '.[] | select(.parent == null and (.participants | length == 2)) | [.id, .participants[].name] | @csv ')

  IFS=$'\n'
  for event in ${events}
  do
    event_id=$(echo "${event}" | cut -d',' -f 1)
    home_team=$(echo "${event}" | cut -d',' -f 2)
    away_team=$(echo "${event}" | cut -d',' -f 3)

    home_sportradar_team_id=$(get_pinnacle_participant_id "${home_team}" "${league_participants}")
    away_sportradar_team_id=$(get_pinnacle_participant_id "${away_team}" "${league_participants}")
    sportradar_id=$(echo "${sport_radar_matches}" | grep ''"${home_sportradar_team_id}"'' | grep ''"${away_sportradar_team_id}"'' | cut -d',' -f 3)
    if [ -n "${sportradar_id}" ]
    then
     echo "${event_id}","${sportradar_id}",pinnacle
    fi
  done
}

pinnacle_betoffers() {
  event_id=$1
  prices=$(curl -s 'https://guest.api.arcadia.pinnacle.com/0.1/matchups/'"${event_id}"'/markets/related/straight' \
  -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
  -H 'X-Device-UUID: 9585db37-f7c6740c-e3129e9b-c7724b36' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -H 'Referer: https://www.pinnacle.com/' \
  -H 'X-API-Key: CmX2KcMrXuFmNg6YFbmTxE0y9CIrOi0R' \
  --compressed \
  | jq -r --arg eventId "${event_id}" '.[]
  | .key as $type_id
  | .matchupId as $market_id
  | (.prices[]
  | [$market_id, $type_id, $eventId, "pinnacle", if (.designation) then .designation else .participantId end, .price, if (.points) then .points else 0 end] | @csv)'\
  | grep "${event_id}", \
  | sed 's/"s;0;m"/"1X2"/g; s/"s;1;m"/"1X2_H1"/g; s/s;0;ou;[^"]*/OVER_UNDER/g' \
  | grep '"1X2"\|"OVER_UNDER"' \
  | awk -F "," -v OFS=','  'function abs(v) {return v < 0 ? -v : v}
            {if($6 < 0) $6=100/abs($6) + 1; else $6=abs($6)/100+1; print}' \
  | cut -d ',' -f 2- \
  | sed 's/home/1/g; s/away/2/g; s/draw/X/g; s/over/Over/g; s/under/Under/g;'
  )

  vig_free "${prices}"

}

#######################################
# zetbet
#######################################

get_sportradar_id_for_zetbet() {
  event=$1
  event_url=$(echo "${event}" |tr -d '"' | sed 's/<a href=/https:\/\/www.zebet.be/g;' | xargs)
  event_id=$(echo "${event_url}" | cut -d '/' -f 6)
  sport_radar_id=$(curl -s "${event_url}" | grep 'LMT.loadStats(' | cut -d ';' -f 1 | cut -d ',' -f 1 | cut -d '(' -f 2)
  echo "${event_id}","${sport_radar_id}","zebet"
}

zetbet_events() {
  league_id=$1
  events=$(curl -s 'https://www.zebet.be/en/competition/'"${league_id}" \
  --compressed \
  | grep 'href="/en/event/')

  IFS=$'\n'
  for event in $events;do
    (get_sportradar_id_for_zetbet "${event}" &)
  done
  wait
}

zetbet_betoffers() {
  event_id=$1

  bet_slip_ids=$(curl -s https://www.zebet.be/en/event/"${event_id}" \
  | grep /en/bettingslip/bet | grep 'odd2\|odd3' | head -n 10 \
  | cut -d ' ' -f 10 | cut -d '=' -f 2 | tr -d '"')

  for id in $bet_slip_ids;do
    (curl -s https://www.zebet.be/en/bettingslip/bet/"${id}" \
    | jq --arg betId $id --raw-output '.body[$betId]
    | .urlEvent as $eventId
    | .libShortActorExternal as $awayTeam
    | .libShortActorDom as $homeTeam
    | .libTypePari as $betType
    | .libQuestion as $points
    | .odds[$betId]
    | [$betType, $eventId, "zetbet", if .long == $homeTeam then "1" elif .short == $awayTeam then "2" else .long end, .odds, if $betType == "Over Under" then $points else 0 end]
    | @csv' \
    | sed 's/Win-Draw-Win/1X2/g; s/Over Under/OVER_UNDER/g;' \
    | sed 's/Over \/ Under //g; s/ goals?//g; s/Draw/X/g;' \
    | grep '"1X2"\|"OVER_UNDER"' &)
  done

  wait
}

#######################################
#  PLAYTECH: MAGIC_BETTING
#######################################

magic_betting_login() {
  port=$1

  login_message='["CONNECT\nprotocol-version:1.5\naccept-version:1.1,1.0\nheart-beat:100000,100000\n\n\u0000"]'

  login_success=null

  while [ "${login_success}" != null ]
  do
    send_message "${login_message}" "${port}"
    message=$(get_message "${port}")
    login_success=$(echo "${message}" | grep CONNECTED)
  done
}

magic_betting_events() {
  league_id=$1
  port=8736

  #sport_radar_matches=$(event_full_feed | grep Soccer)

  url=$(node ./magic_betting_ws_url.js)

  create_connection "${url}" "${port}"
  ws_pid=$!

  magic_betting_login "${port}"

  events_parsed=null

  while [ "${events_parsed}" == null ]
  do
    events_message='["SUBSCRIBE\nid:/api/eventgroups/'"${league_id}"'-all-match-events-grouped-by-type\ndestination:/api/eventgroups/'"${league_id}"'-all-match-events-grouped-by-type\nlocale:nl\n\n\u0000"]'
    send_message "${events_message}" "${port}"
    events_parsed=$(get_message "${port}" | jq --raw-output '.')
  done

  echo "${events_parsed}"


  kill -9 "${ws_pid}"

}

magic_betting_betoffers() {
  event_id=$1
  port=8809

  create_connection eu-swarm-ws-re.bcapps.net "${port}"
  ws_pid=$!

  starcasino_login "${port}"

  rid=$(date +%s)

  echo '{"command":"get","params":{"source":"betting","what":{"game":["id","show_type","markets_count","start_ts","is_live","is_blocked","is_neutral_venue","team1_id","team2_id","game_number","text_info","is_stat_available","type","info","team1_name","team2_name","tv_info","stats","add_info_name"],"market":["id","col_count","type","name_template","sequence","point_sequence","express_id","cashout","display_key","display_sub_key","group_id","name","group_name","order","extra_info","group_order"],"event":["order","id","type_1","type","type_id","original_order","name","price","nonrunner","ew_allowed","sp_enabled","extra_info","base","home_value","away_value","display_column"]},"where":{"game":{"id":'"${event_id}"'}},"subscribe":false},"rid":'"${rid}"'}' \
  | nc 127.0.0.1 "${port}"

  get_message "${port}" \
   | jq --raw-output '.data.data.game["'"${event_id}"'"] | .id as $eventId | .market
  | to_entries
  | .[]
  | .value
  | .type as $betType
  | .event
  | to_entries
  | .[]
  | .value
  | [$betType, $eventId, "starcasino", .type, .price, .base]
  | @csv' \
  | sed 's/"OverUnder"/"OVER_UNDER"/g; s/"P1XP2"/"1X2"/g; s/"P1"/"1"/g; s/"P2"/"2"/g; ' \
  | grep '"1X2"\|"OVER_UNDER"'


  kill -9 "${ws_pid}"
}


#######################################
#  BET90
#######################################

bet90_events() {
  curl 'https://bet90.be/Sports/SportLeagueGames' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
  -H 'Accept: */*' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'Origin: https://bet90.be' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://bet90.be/Sports' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Cookie: ASP.NET_SessionId=neefmtmnpmaq4fptqh2evgyl; Culture=nl' \
  --data-raw '{"leagueId":"30","categoryId":19,"sportId":1}' \
  --compressed \
  | xmllint --html --xpath '//div[@class="divTableBody"]'
}


