#!/bin/bash

source sportradar
source books

books='pinnacle sbtech betcenter bingoal goldenpalace meridian ladbrokes zetbet betconstruct'
matches=$(event_full_feed | grep Soccer)
league_ids=$(echo "${matches}" | cut -d ',' -f 2 | sort -u)

get_all_leagues_for_each_book() {
  for league_id in $league_ids;do
    jq_string='.["'"${league_id}"'"]'
    mapped_leagues=$(jq "${jq_string}" ./resources/league_map.json)
    if [[ "${mapped_leagues}" != 'null' ]]
    then
      IFS=$' '
      for book in $books;do
        echo "${mapped_leagues}" | jq '.["'"${book}"'"]' |tr -d '"' | sort -u >> "${book}"_leagues &
      done
      wait
    fi
  done
}

get_all_leagues_for_each_book "${league_ids}"

for book in $books;do
  for i in {1..10};
  do
    if [ ! -f "${book}"_leagues ]
    then sleep 2
    else
      book_leagues=$(cat "${book}"_leagues | sort -u)
      IFS=$'\n'
      for book_league_id in $book_leagues;do
        if [ "${book}" == betconstruct ]
        then
          "${book}"_events "${book_league_id}" >> "${book}"_events.csv
        elif [ "${book}" == starcasino ]
        then
          "${book}"_events "${book_league_id}" >> "${book}"_events.csv
        else "${book}"_events "${book_league_id}" >> "${book}"_events.csv &
        fi
      done
      wait
      break
    fi
  done
done

pinnacle_events=$(cat pinnacle_events.csv)

create_json_body() {
  pinnacle_event=$1
  sport_radar_id=$(echo "${pinnacle_event}" | cut -d ',' -f 2 | sort -u)
  echo '"sport_radar": '"${sport_radar_id}"','
  IFS=' '
  for book in $books;do
    for i in {1..10};
    do
      if [ ! -f "${book}"_events.csv ]
      then
        sleep 2
      else
        book_event_id=$(grep "${sport_radar_id}" "${book}"_events.csv | sort -u | cut -d ',' -f 1 | tr -d '"' | sort -u)
        echo '"'"${book}"'": '"${book_event_id}",
        break
      fi
    done
  done
}

IFS=$'\n'
for pinnacle_event in $pinnacle_events;do
  body=$(create_json_body "${pinnacle_event}" | rev)
  body_corrected=$(echo ${body/,/} | rev)
  echo {"${body_corrected}"}
done

rm *_events.csv
rm *_leagues

