#!/bin/bash

get_sport_radar_id() {
  local event_id=$1
  local league=$2
  local book='"kambi"'
  local sportradar_match=$(curl -s 'https://nl.unibet.be/kambi-rest-api/sportradar/widget/event/nl/'"${event_id}")
  local sportradar_widget_url=$(echo "${sportradar_match}" | jq '.content | .[0].Resource')
  IFS='matchId='
  read -ra ADDR <<<"$sportradar_widget_url"
  match_id="${ADDR[*]: -1}"
  echo "${event_id}","${match_id%?}","${book}","${league}"
}

get_events() {
  league_id=$1
  league=$2
  event_ids=$(curl -s 'https://eu-offering.kambicdn.org/offering/v2018/ubbe/event/group/'"${league_id}"'.json?includeParticipants=false' \
  | jq '.events[] | select(.tags[] == "MATCH") | .id')

  for event_id in ${event_ids}; do
      get_sport_radar_id "${event_id}" "${league}" &
  done
  wait 
}

get_events 1000094991 '"ligue_1"' &
get_events 1000094965 '"jupiler_pro_league"' &
get_events 1000094985 '"premier_league"' &
get_events 1000095049 '"la_liga"' &
get_events 1000095001 '"serie_a"' &
get_events 1000094994 '"bundesliga"' &
get_events 1000094980 '"eredivisie"' &
get_events 1000093381 '"champions_league"' &
get_events 2000051195 '"europa_league"'

wait








