build:
	docker build . -t pjtest \
	&& docker tag pjtest europe-west1-docker.pkg.dev/trusty-cacao-327717/valuebets/matches_of_the_day:test \
	&& docker push europe-west1-docker.pkg.dev/trusty-cacao-327717/valuebets/matches_of_the_day:test