#!/bin/bash

season_over_under() {
    season_id=$1
    local output=$(curl 'https://lsc.fn.sportradar.com/sportradar/en/Europe:Berlin/gismo/stats_season_overunder/'$season_id)
    echo $output
}

season_over_under $1