build:
	docker build . -t kambitest \
	&& docker tag kambitest europe-west1-docker.pkg.dev/trusty-cacao-327717/valuebets/kambitest:test \
	&& docker push europe-west1-docker.pkg.dev/trusty-cacao-327717/valuebets/kambitest:test
