#!/bin/bash

sport_radar_matches=$1
sport_radar_league_ids=$(echo "${sport_radar_matches}" | cut -d ',' -f 2)
bwin_league_ids=$(grep "${sport_radar_league_ids}" pinnacle_sportradar_league_mapping.csv | cut -d ',' -f 5)

get_events() {
  local league_id=$1
  local book='"bwin"'

  curl -G -s 'https://cds-api.bwin.be/bettingoffer/fixtures' \
  -d x-bwin-accessid=NTE3MjUyZDUtNGU5Ni00MTkwLWJkMGQtMDhmOGViNGNiNmRk \
  -d lang=en \
  -d country=BE \
  -d userCountry=BE \
  -d fixtureTypes=Standard \
  -d state=Latest \
  -d offerMapping=Filtered \
  -d offerCategories=Gridable \
  -d fixtureCategories=Gridable,NonGridable,Other \
  -d competitionIds="${league_id}" \
  -d skip=0 \
  -d take=50 \
  -d sortBy=Tags \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36' \
  | jq --raw-output '.fixtures[] | [.id, .addons.liveMatchTracker.sportradarId // .addons.betRadar, "bwin"] | @csv'
}

for league_id in $bwin_league_ids;do
  get_events "${league_id}" &
done

