#!/bin/bash

description=$1
schedule=$2
service_uri=$3
body=$4
name=$5

gcloud scheduler jobs create http ${name} \
	  --description "${description}" \
	  --schedule "${schedule}" \
	  --time-zone "Europe/Brussels" \
	  --uri "${service_uri}" \
	  --http-method POST \
	  --oidc-service-account-email cloud-run-scheduler@trusty-cacao-327717.iam.gserviceaccount.com \
	  --message-body "${body}"
