#!/bin/bash

./delete_jobs value-bets
./delete_jobs closing-lines

filterSports=Soccer

jupiler_pro_league=38
bundesliga=42
premier_league=1
ligue_1=4
serie_a=33
la_liga=36
eredivisie=39
argentina=68

# get sport radar
matches=$(./event_full_feed \
| grep "${filterSports}" \
| grep ",${jupiler_pro_league},\|,${bundesliga},\|,${premier_league},\|,${ligue_1},\|,${serie_a},\|,${la_liga},\|,${eredivisie},\|,${argentina},")

# get books
sbtech=$(./sbtech)
pinnacle=$(./pinnacle "${matches}")
wait

IFS=$'\n'
for match in $matches;do
  sport_radar_id=$(echo "${match}" | cut -d ',' -f 3)
  start_time=$(echo "${match}" | cut -d ',' -f 4 |tr -d ':' |tr -d '"')

  # set system date to start time
  date "${start_time}"
  value_bet_start_hour=$(date -v-3H +%H)
  value_bet_start_minutes=$(date -v-3H +%M)
  closing_line_start_hour=$(date -v-1M +%H)
  closing_line_start_minutes=$(date -v-1M +%M)
  value_bet_schedule=""${value_bet_start_minutes}" "${value_bet_start_hour}" * * *"
  closing_line_schedule=""${closing_line_start_minutes}" "${closing_line_start_hour}" * * *"

  sbtech_id=$(echo "${sbtech}" | grep "${sport_radar_id}" | cut -d ',' -f 1 | tr -d '"')
  pinnacle_id=$(echo "${pinnacle}" | grep "${sport_radar_id}" | cut -d ',' -f 1)

  value_bet_body="${sport_radar_id}","${start_time}","${pinnacle_id}","${sbtech_id}"
  closing_line_body="${pinnacle_id}","${sport_radar_id}"

  value_bet_service_uri="https://find-value-bets-sah63l2xba-ew.a.run.app"
  closing_line_service_uri="https://closing-lines-sah63l2xba-ew.a.run.app"
  ./create_job "find-value-bets" "${value_bet_schedule}" "${value_bet_service_uri}" "${value_bet_body}" "find-value-bets-${sport_radar_id}"
  ./create_job "find-closing-lines" "${closing_line_schedule}" "${closing_line_service_uri}" "${closing_line_body}" "find-closing-lines-${sport_radar_id}"
done



