#!/bin/bash

filterSports=Soccer

jupiler_pro_league=38
bundesliga=42
premier_league=1
ligue_1=4
serie_a=33
la_liga=36
eredivisie=39

# get sport radar
matches=$(./event_full_feed \
| grep "${filterSports}" \
| grep ",${jupiler_pro_league},\|,${bundesliga},\|,${premier_league},\|,${ligue_1},\|,${serie_a},\|,${la_liga},\|,${eredivisie},")

# get books
sbtech=$(./sbtech)
pinnacle=$(./pinnacle "${matches}")
wait

create_scheduled_job() {
  schedule=$1
  sport_radar_id=$2
  description=$3
  service_uri=$4
  	gcloud scheduler jobs create http my-hourly-job \
	  --description "${description}" \
	  --schedule "${schedule}" \
	  --time-zone "Europe/Berlin" \
	  --uri "${service_uri}" \
	  --http-method GET \
	  --oidc-service-account-email cloud-run-scheduler@trusty-cacao-327717.iam.gserviceaccount.com \
	  --message-body "${sport_radar_id}"
}

IFS=$'\n'
for match in $matches;do
  match_id=$(echo "${match}" | cut -d ',' -f 3)
  start_time=$(echo "${match}" | cut -d ',' -f 4)
  sbtech_id=$(echo "${sbtech}" | grep "${match_id}" | cut -d ',' -f 1 | tr -d '"')
  pinnacle_id=$(echo "${pinnacle}" | grep "${match_id}" | cut -d ',' -f 1)
  hour=$(echo "${start_time}" | tr -d '"' | cut -d ':' -f 1)
  minute=$(echo "${start_time}" | tr -d '"' | cut -d ':' -f 2)
  range=3
  hour_minus=$(echo "$((hour-$range))")
  schedule=""${minute}" "${hour_minus}" * * *"
  service_uri="https://find-value-bets-sah63l2xba-ew.a.run.app"
  description=\""Find value bets for sport radar id: "${match_id}"\""
  create_scheduled_job "${schedule}" "${match_id}" "${description}" "${service_uri}"
  #echo "${match_id}","${start_time}","${pinnacle_id}","${sbtech_id}"
done



