#!/bin/bash

sport_radar_matches=$1
sport_radar_league_ids=$(echo "${sport_radar_matches}" | cut -d ',' -f 2)
meridian_league_ids=$(grep "${sport_radar_league_ids}" pinnacle_sportradar_league_mapping.csv | cut -d ',' -f 7 | sort -u)

get_events() {
  url=$1
  curl -s "${url}" | jq --raw-output '.[0].events[] | [.id, .betradarUnified["id"], "meridian"] | @csv'
}

for meridian_league_id in $meridian_league_ids;do
  get_events "${meridian_league_id}"
done