#!/bin/bash
get_pinnacle_participant_id() {
  name=$1
  jq_string='.['"${name}"']'
  participant=$(cat < pinnacle_sportradar_participant.json | jq "${jq_string}")
  echo "${participant}"
}

sport_radar_matches=$1
sport_radar_league_ids=$(echo "${sport_radar_matches}" | cut -d ',' -f 2)
pinnacle_league_ids=$(grep "${sport_radar_league_ids}" pinnacle_sportradar_league_mapping.csv | cut -d ',' -f 3)
IFS=$'\n'
for league_id in $pinnacle_league_ids;do
    events=$(curl -s 'https://guest.api.arcadia.pinnacle.com/0.1/leagues/'"${league_id}"'/matchups' \
  -H 'authority: guest.api.arcadia.pinnacle_betoffers.com' \
  -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
  -H 'accept: application/json' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36' \
  -H 'x-api-key: CmX2KcMrXuFmNg6YFbmTxE0y9CIrOi0R' \
  -H 'content-type: application/json' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed \
  | jq --raw-output '.[] | select(.parent == null and (.participants | length == 2)) | [.id, .participants[].name] | @csv ')

      for event in ${events}
      do
        event_id=$(echo "${event}" | cut -d',' -f 1)
        home_team=$(echo "${event}" | cut -d',' -f 2)
        away_team=$(echo "${event}" | cut -d',' -f 3)
        home_sportradar_team_id=$(get_pinnacle_participant_id "${home_team}")
        away_sportradar_team_id=$(get_pinnacle_participant_id "${away_team}")
        sportradar_id=$(echo "${sport_radar_matches}" | grep ''"${home_sportradar_team_id}"'' | grep ''"${away_sportradar_team_id}"'' | cut -d',' -f 3)
        if [ -n "${sportradar_id}" ]
        then
        echo "${event_id}","${sportradar_id}",pinnacle_betoffers
        fi
      done
done





