#!/bin/bash

sport_radar_matches=$1
sport_radar_league_ids=$(echo "${sport_radar_matches}" | cut -d ',' -f 2)
sbtech_league_ids=$(grep "${sport_radar_league_ids}" pinnacle_sportradar_league_mapping.csv | cut -d ',' -f 4 | sort -u)

get_token() {
    token_message=$(curl 'https://sbapi.sbtech.com/betfirst/auth/platform/v1/api/GetTokenBySiteId/28')

    IFS=' = '
    read -a strarr <<<"${token_message}"
    token_raw="${strarr[1]}"

    token_temp=${token_raw%\'}
    echo ${token_temp#\'}
}

get_events() {
    local token=$1
    local book=betfirst
    local league_id=$2

    curl -s 'https://sbapi.sbtech.com/'"${book}"'/sportsdata/v2/events?query=$filter=leagueId%20eq%20%27'"${league_id}"'%27&locale=en' \
    -H 'accept: application/json, text/javascript, */*; q=0.01' \
    -H 'authorization: Bearer '"${token}" \
    -H 'content-type: application/json-patch+json' \
    --compressed \
    | jq --raw-output '.data.events[]
    | .id as $id
    | .media[]
    | select(.providerName == "BetRadarV3")
    | [$id, .providerEventId, "sbtech"]
    | @csv' \
    | sort -u

}

token=$(get_token)

for league_id in $sbtech_league_ids;do
  get_events "${token}" "${league_id}" &
done

wait












