#!/bin/bash

bet_offers=$1

echo "${bet_offers}"

# example: "OVER_UNDER","1402247459","pinnacle_betoffers","Under",1.64103,2.5,1.5801

prep_statement() {
  IFS=$'\n'
  for bet_offer in $bet_offers;do
    bet_type=$(echo "${bet_offer}" | cut -d ',' -f 1 |tr -d '"')
    event_id=$(echo "${bet_offer}" | cut -d ',' -f 2|tr -d '"')
    book=$(echo "${bet_offer}" | cut -d ',' -f 3 |tr -d '"')
    bet_option=$(echo "${bet_offer}" | cut -d ',' -f 4 |tr -d '"')
    price=$(echo "${bet_offer}" | cut -d ',' -f 5)
    points=$(echo "${bet_offer}" | cut -d ',' -f 6)
    sport_radar_id=$(echo "${bet_offer}" | cut -d ',' -f 7 |tr -d '"')
    vig_free_price=$(echo "${bet_offer}" | cut -d ',' -f 8)
    echo "('${bet_type}', '${event_id}', '${book}', '${bet_option}', ${price}, ${points}, ${vig_free_price}, ${sport_radar_id}), "
  done
}

export SNOWSQL_ACCOUNT=bs92548.europe-west4.gcp
export SNOWSQL_USER=demuinckpieterjan
export SNOWSQL_PWD=$(gcloud secrets versions access latest --secret="snowflake_pass")
export SNOWSQL_ROLE=SYSADMIN
export SNOWSQL_DATABASE=PROTRADER
export SNOWSQL_WAREHOUSE=COMPUTE_WH
export SNOWSQL_SCHEMA=VALUE_BETS


values=$(prep_statement)

modified=$(echo ${values} |rev | cut -c2- |rev)

echo "${modified}"

snowsql -q "insert into closing_lines(bet_type, event_id, book, bet_option, price, points, vig_free_price, sport_radar_id) values ${modified}"
