publish_image:
	docker build . -t closing_lines \
	&& docker tag closing_lines europe-west1-docker.pkg.dev/trusty-cacao-327717/valuebets/closing_lines:test \
	&& docker push europe-west1-docker.pkg.dev/trusty-cacao-327717/valuebets/closing_lines:test
