#!/bin/bash

event_id=$1

curl -s 'https://oddsservice.betcenter.be/odds/getGames/8' \
  -H 'x-language: 2' \
  -H 'x-brand: 7' \
  --data-raw '{"gameIds":['"${event_id}"'],"gameTypes":[1,4,5],"jurisdictionId":30}' \
  | jq --raw-output '.games[]
  | .id as $eventId
  | .markets[]
  | .id as $betType
  | .anchor as $points
  | .tips[]
  | [$betType, $eventId, "betcenter", .text, .odds / 100, $points // 0] | @csv' \
  | sed 's/22242/1X2/g; s/22462/OVER_UNDER/g; s/22252/OVER_UNDER/g; s/22482/OVER_UNDER/g; s/22492/OVER_UNDER/g; s/22502/OVER_UNDER/g; s/22512/OVER_UNDER/g; s/22472/OVER_UNDER/g' \
  | sed 's/"0-1"/"Under"/g; s/"2+"/"Over"/g; s/"0-2"/"Under"/g; s/"0-3"/"Under"/g; s/"0-4"/"Under"/g; s/"0-5"/"Under"/g; s/"0-6"/"Under"/g; s/"1+"/"Over"/g; s/"2+"/"Over"/g; s/"3+"/"Over"/g; s/"4+"/"Over"/g; s/"5+"/"Over"/g; s/"6+"/"Over"/g; s/"7+"/"Over"/g; s/"0"/"Under"/g' \
  | grep '1X2\|OVER_UNDER'