#!/bin/bash

event_id=$1

bet_slip_ids=$(curl -s https://www.zebet.be/en/event/hji92-club_brugge_kv_kortrijk \
| grep -m3 /en/bettingslip/bet \
| cut -d ' ' -f 10 | cut -d '=' -f 2 | tr -d '"')

for id in $bet_slip_ids;do
  curl -s https://www.zebet.be/en/bettingslip/bet/"${id}" \
  | jq --arg betId $id --raw-output '.body[$betId]
  | .urlEvent as $eventId
  | .libShortActorExternal as $awayTeam
  | .libShortActorDom as $homeTeam
  | .libTypePari as $betType
  | .odds[$betId]
  | [$betType, $eventId, "zetbet", if .long == $homeTeam then "1" elif .short == $awayTeam then "2" else "X" end, .odds, 0]
  | @csv' \
  | sed 's/Win-Draw-Win/1X2/g'
done