#!/bin/bash

match=$1

echo MATCH: "${match}"

sportradar_id=$(echo "${match}" | jq --raw-output '.sport_radar')
pinnacle_id=$(echo "${match}" | jq --raw-output '.pinnacle')
sbtech_id=$(echo "${match}" | jq --raw-output '.sbtech')
betcenter_id=$(echo "${match}" | jq --raw-output '.betcenter')
meridian_id=$(echo "${match}" | jq --raw-output '.meridian')
goldenpalace_id=$(echo "${match}" | jq --raw-output '.goldenpalace')
ladbrokes_id=$(echo "${match}" | jq --raw-output '.ladbrokes')
bingoal_id=$(echo "${match}" | jq --raw-output '.bingoal')
zetbet_id=$(echo "${match}" | jq --raw-output '.zetbet')
starcasino_id=$(echo "${match}" | jq --raw-output '.starcasino')

./books/sbtech "${sbtech_id}" "${sportradar_id}" > sbtech_"${sportradar_id}"_betoffers.csv &
./books/pinnacle "${pinnacle_id}" "${sportradar_id}" &
./books/betcenter "${betcenter_id}" > betcenter_"${sportradar_id}"_betoffers.csv &
./books/meridian "${meridian_id}" > meridian_"${sportradar_id}"_betoffers.csv &
./books/goldenpalace "${goldenpalace_id}" > goldenpalace_"${sportradar_id}"_betoffers.csv &
./books/ladbrokes "${ladbrokes_id}" > ladbrokes_"${sportradar_id}"_betoffers.csv &
./books/bingoal "${bingoal_id}" > bingoal_"${sportradar_id}"_betoffers.csv &
./books/zetbet "${zetbet_id}" > zetbet_"${sportradar_id}"_betoffers.csv &
./books/starcasino "${starcasino_id}" > starcasino_"${sportradar_id}"_betoffers.csv &
wait

betoffers=$(cat *_betoffers.csv | grep -v "pinnacle" | grep -w "OVER_UNDER\|1X2\|1X2_H1")
predictions=$(cat *_pinnacle_betoffers.csv | grep "pinnacle")

find_value() {
    IFS=$'\n'
    for betoffer in ${betoffers};do
      bet_type=$(echo "${betoffer}" | cut -d ',' -f 1)
      bet_option=$(echo "${betoffer}" | cut -d ',' -f 4)
      price=$(echo "${betoffer}" | cut -d ',' -f 5 |tr -d '"')
      bet_line=$(echo "${betoffer}" | cut -d ',' -f 6 |tr -d '"')
      prediction=$(echo "${predictions}" | grep -w "${bet_type}" | grep "${bet_option}" | grep ",${bet_line}," | cut -d ',' -f 7)
      if [ -n "$prediction" ]; then
        value=$(./utils/calculate_value "${price}" "${prediction}")
        # apply filters
        if (( $(echo "$value > 0.01" |bc -l) && $(echo "$price < 4.0" |bc -l))); then
            echo "${betoffer}","${value}","${sportradar_id}","${prediction}"
        fi
      fi
    done
}


filter_value_bets() {
  value_bets=$1

  value_bets_sorted=$(echo "${value_bets}" | sort -t ',' -k1,1 -k4,4 -k6,6 -rk7,7)
  max_value_bets=$(echo "${value_bets}" | mlr --ocsv stats1 -a max -f 7 -g 1,4,6)

  IFS=$'\n'
  for line in $max_value_bets;do
    bet_type=$(echo "${line}" | cut -d ',' -f 1)
    bet_option=$(echo "${line}" | cut -d ',' -f 2)
    bet_option_clean="${bet_option%\"}"
    bet_option_clean="${bet_option_clean#\"}"
    bet_option_clean="${bet_option_clean%\"}"
    bet_option_clean="${bet_option_clean#\"}"
    bet_line=$(echo "${line}" | cut -d ',' -f 3)
    price=$(echo "${line}" | cut -d ',' -f 4)
    echo "${value_bets_sorted}"  | grep "${price}" |grep "${bet_option_clean}" | grep "${bet_line}" | head -1
  done
}

value_bets=$(find_value)
#value_bets_filtered=$(filter_value_bets "${value_bets}")
#echo "${value_bets_filtered}"

echo "${value_bets}"

./snowflake/insert_value_bets_snowflake "${value_bets}"

rm *betoffers.csv




