#!/bin/bash

match=$1
sportradar_id=$(echo "${match}" | cut -d ',' -f 1)
pinnacle_id=$(echo "${match}" | cut -d ',' -f 3)
sbtech_id=$(echo "${match}" | cut -d ',' -f 4)

./sbtech_betoffers "${sbtech_id}" "${sportradar_id}" &
./pinnacle_betoffers "${pinnacle_id}" "${sportradar_id}"

wait

betoffers=$(cat *_betoffers.csv | grep -v "pinnacle" | grep -w "OVER_UNDER\|1X2\|1X2_H1")
predictions=$(cat *_pinnacle_betoffers.csv | grep "pinnacle")

find_value() {
    IFS=$'\n'
    for betoffer in ${betoffers};do
      bet_type=$(echo "${betoffer}" | cut -d ',' -f 1)
      bet_option=$(echo "${betoffer}" | cut -d ',' -f 4)
      price=$(echo "${betoffer}" | cut -d ',' -f 5)
      bet_line=$(echo "${betoffer}" | cut -d ',' -f 6)
      prediction=$(echo "${predictions}" | grep -w "${bet_type}" | grep "${bet_option}" | grep ",${bet_line}," | cut -d ',' -f 7)
      if [ -n "$prediction" ]; then
        value=$(./utils/calculate_value "${price}" "${prediction}")
        # apply filters
        if (( $(echo "$value > 0.01" |bc -l) && $(echo "$price < 4.0" |bc -l))); then
            echo "${betoffer}","${value}"
        fi
      fi
    done
}


filter_value_bets() {
  value_bets=$1

  value_bets_sorted=$(echo "${value_bets}" | sort -t ',' -k1,1 -k4,4 -k6,6 -rk7,7)
  max_value_bets=$(echo "${value_bets}" | mlr --ocsv stats1 -a max -f 7 -g 1,4,6)

  IFS=$'\n'
  for line in $max_value_bets;do
    bet_type=$(echo "${line}" | cut -d ',' -f 1)
    bet_option=$(echo "${line}" | cut -d ',' -f 2)
    bet_option_clean="${bet_option%\"}"
    bet_option_clean="${bet_option_clean#\"}"
    bet_option_clean="${bet_option_clean%\"}"
    bet_option_clean="${bet_option_clean#\"}"
    bet_line=$(echo "${line}" | cut -d ',' -f 3)
    price=$(echo "${line}" | cut -d ',' -f 4)
    echo "${value_bets_sorted}"  | grep "${price}" |grep "${bet_option_clean}" | grep "${bet_line}" | head -1
  done
}

value_bets=$(find_value)
value_bets_filtered=$(filter_value_bets "${value_bets}")
echo "${value_bets_filtered}"



rm *betoffers.csv




