#!/bin/bash

value_bets=$1

# example: "1X2",12345,"betfirst","1",2.34,0,0.0489

prep_statement() {
  IFS=$'\n'
  for value_bet in $value_bets;do
    bet_type=$(echo "${value_bet}" | cut -d ',' -f 1 |tr -d '"')
    event_id=$(echo "${value_bet}" | cut -d ',' -f 2)
    book=$(echo "${value_bet}" | cut -d ',' -f 3 |tr -d '"')
    bet_option=$(echo "${value_bet}" | cut -d ',' -f 4 |tr -d '"')
    price=$(echo "${value_bet}" | cut -d ',' -f 5)
    points=$(echo "${value_bet}" | cut -d ',' -f 6)
    edge=$(echo "${value_bet}" | cut -d ',' -f 7)
    echo "('${bet_type}', '${event_id}', '${book}', '${bet_option}', ${price}, ${points}, ${edge}), "
  done
}

export SNOWSQL_ACCOUNT=bs92548.europe-west4.gcp
export SNOWSQL_USER=demuinckpieterjan
export SNOWSQL_PWD=$(gcloud secrets versions access latest --secret="snowflake_pass")
export SNOWSQL_ROLE=SYSADMIN
export SNOWSQL_DATABASE=PROTRADER
export SNOWSQL_WAREHOUSE=COMPUTE_WH
export SNOWSQL_SCHEMA=VALUE_BETS


values=$(prep_statement)

modified=$(echo "${values}" |rev | cut -c3- |rev)

echo "${modified}"

snowsql -q "insert into value_bets(bet_type, event_id, book, bet_option, price, points, edge) values ${modified}"
