build:
	docker build . -t find_value_bets \
	&& docker tag find_value_bets europe-west1-docker.pkg.dev/trusty-cacao-327717/valuebets/find_value_bets:test \
	&& docker push europe-west1-docker.pkg.dev/trusty-cacao-327717/valuebets/find_value_bets:test
