#!/bin/bash

# create persistent websocket client connection
# call nc 127.0.0.1:1234 to get messages

echo GETTING BCAPPS

PORT=$1

websocat -t -B 1000000 -E tcp-l:127.0.0.1:"${PORT}" reuse-raw:wss://eu-swarm-ws-re.bcapps.net --max-messages-rev 1&
WS_PID=$!
echo created websocket client with pid "${WS_PID}"

rid=$(date +%s)

nc 127.0.0.1 "${PORT}"
echo about to log in...
echo '{"command":"request_session","params":{"language":"eng","site_id":"385","release_date":"15/09/2020-16:48"},"rid":"'"${rid}"'"}' \
| nc 127.0.0.1 "${PORT}"
nc 127.0.0.1 "${PORT}"

get_events() {
  local league_id=$1
  local league=$2
  echo '{"command":"get","params":{"source":"betting","what":{"game":["id", "team1_name", "team1_id", "team2_name", "team2_id"]},"where":{"competition":{"id":'"${league_id}"'}},"subscribe":true},"rid":"'"${rid}"'"}' \
  | nc 127.0.0.1 "${PORT}"

  nc 127.0.0.1 "${PORT}" | jq --raw-output '.data.data.game | values[] | [.id, .team1_name, .team2_name, "bcapps",'"${league}"'] | @csv' >> "${league}"_bcapps_league_events.csv
}

get_events 538 '"premier_league"'
get_events 545 '"la_liga"'
get_events 541 '"bundesliga"'
get_events 543 '"serie_a"'
get_events 557 '"jupiler_pro_league"'
get_events 548 '"ligue_1"'

cat *_bcapps_league_events.csv >> bcapps_events.csv
rm *_bcapps_league_events.csv

echo kill websocket client...
kill -9 "${WS_PID}"

echo GOT BCAPPS

