#!/bin/bash

init() {
    curl -s 'https://www.bingoal.be/nl/Sport' --header "accept-encoding: application/json" -D bingoal_headers > bingoal_response
}

get_cookies() {
  cookie_raw=$(cat bingoal_headers | grep -m 2 'SET-COOKIE: ' | cut -c 12-)
  rm bingoal_headers
  echo "${cookie_raw//[$'\t\r\n']}"
}

get_k_parameter(){
  k=$(cat bingoal_response | grep '_k = ' | cut -d\' -f 2)
  rm bingoal_response
  echo "${k}"
}

get_events() {
  cookie=$1
  league=$2
  league_id=$3
  k=$4

  curl -s 'https://www.bingoal.be/A/sport' \
    -H 'X-Requested-With: XMLHttpRequest' \
    -H 'Cookie: '"${cookie}" \
    --data-raw 'func=sport&action=SOCCER&id='"${league_id}"'&k='"${k}" \
    --compressed \
    | jq --raw-output '.sports[].matches[] | [.ID, .betradarID, "bingoal", '"${league}"'] | @csv' >> "${league}"_bingoal_league_events.csv
}

init
cookies=$(get_cookies)
k=$(get_k_parameter)

get_events "${cookies}" '"premier_league"' 35 "${k}" &
get_events "${cookies}" '"jupiler_pro_league"' 25 "${k}" &
get_events "${cookies}" '"serie_a"' 39 "${k}" &
get_events "${cookies}" '"la_liga"' 37 "${k}" &
get_events "${cookies}" '"ligue_1"' 26 "${k}" &
get_events "${cookies}" '"bundesliga"' 38 "${k}"

wait

cat *_bingoal_league_events.csv >> bingoal_events.csv
rm *_bingoal_league_events.csv

