#!/bin/bash

# create persistent websocket client connection
# call nc 127.0.0.1:1234 to get messages

websocat -t -E tcp-l:127.0.0.1:1235 reuse-raw:wss://wss02.circus.be --max-messages-rev 1&

echo created websocket client with pid

nc 127.0.0.1 1235

echo about to log in...

echo '{"Id":"d91df36e-ddc3-ca27-5f38-689862a5d59b","TTL":10,"MessageType":1,"Message":"{\"NodeType\":1,\"Identity\":\"fbb21005-c3a9-43ff-96f1-a8f0289e86f2\",\"EncryptionKey\":\"\",\"ClientInformations\":{\"AppName\":\"Front;Registration-Origin: default\",\"ClientType\":\"Responsive\",\"Version\":\"1.0.0\",\"UserAgent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36\",\"LanguageCode\":\"en\",\"RoomDomainName\":\"CIRCUS\"}}"}' \
| nc 127.0.0.1 1235

nc 127.0.0.1 1235

echo '{"Id":"7d96347e-1052-2505-c505-4355f27f458e","TTL":10,"MessageType":1000,"Message":"{\"Direction\":1,\"Id\":\"5c2d1a74-d99a-87e8-e4d7-a3b607694ffa\",\"Requests\":[{\"Id\":\"fc3c2e89-99f3-44b8-24cc-f04fb1689ca2\",\"Type\":201,\"Identifier\":\"GetLeaguesDataSourceFromCache\",\"AuthRequired\":false,\"Content\":\"{\\\"Entity\\\":{\\\"Language\\\":\\\"en\\\",\\\"BettingActivity\\\":0,\\\"PageNumber\\\":0,\\\"IncludeSportList\\\":true,\\\"EventType\\\":0,\\\"SportId\\\":844,\\\"RegionId\\\":0,\\\"LeagueId\\\":1351379392,\\\"EventId\\\":2816197201}}\"}],\"Groups\":[]}"}' \
| nc 127.0.0.1 1235

nc 127.0.0.1 1235 > output_circus

kill "${pid}"

