#!/bin/bash

echo START GETTING Events

./meridian &
./altenar &
./cashpoint &
./bwin &
./kambi &
./betway &
./ladbrokes &
./sbtech &
./bingoal &
./betconstruct
wait 

echo event_id,sportradar_id,book,league > events.csv
cat *_events.csv >> events.csv
rm *_events.csv
# TODO remove empty lines first from events.csv
sportradar_ids=$(mlr --csv --headerless-csv-output filter -S '$sportradar_id =~ "^[0-9]{8}$"' then uniq -g sportradar_id events.csv)

echo GET sportradar match info
for id in ${sportradar_ids}
do ./sportradar/match_info "${id}" | jq --raw-output '.doc[0].data.match | [._id, ._dt.date, ._dt.time, ._dt.tz, .teams.home._id, .teams.home.name, .teams.away._id, .teams.away.name] | @csv' > "${id}"_sportradar_match &
done

wait
echo sportradar_id,event_date,event_time,event_time_zone,home_id,home_name,away_id,away_name > sportradar_events.csv
cat *_sportradar_match >> sportradar_events.csv
rm *_sportradar_match
echo GOT sportradar match info


