#!/bin/bash

echo START GETTING Events

./meridian &
./altenar &
./cashpoint &
./bwin &
./kambi &
./betway &
./ladbrokes &
./sbtech &
./bingoal &
./betconstruct
wait 

echo event_id,sportradar_id,book,league > events.csv
cat *_events.csv >> events.csv
rm *_events.csv
mlr --csv filter -S '$sportradar_id =~ "^[0-9]{8}$"' then uniq -g sportradar_id events.csv > sportradar_ids

