#!/bin/bash

get_participant_id() {
  name=$1
  jq_string='.['"${name}"']'
  participant=$(cat < pinnacle_sportradar.json | jq "${jq_string}")
  echo "${participant}"
}

get_events() {
  league=$1
  league_id=$2

  curl -s 'https://guest.api.arcadia.pinnacle.com/0.1/leagues/'"${league_id}"'/matchups' \
    -H 'authority: guest.api.arcadia.pinnacle.com' \
    -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
    -H 'accept: application/json' \
    -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36' \
    -H 'x-api-key: CmX2KcMrXuFmNg6YFbmTxE0y9CIrOi0R' \
    -H 'content-type: application/json' \
    -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
    --compressed \
    | jq --raw-output '.[] | select(.parent == null) | [.id, .participants[].name, "pinnacle",'"${league}"'] | @csv ' >> "${league}"_pinnacle_league_events.csv

}

echo GETTING PINNACLE...

get_events '"bundesliga"' 1842 &
get_events '"la_liga"' 2196 &
get_events '"premier_league"' 1980 &
get_events '"serie_a"' 2436 &
get_events '"ligue_1"' 2036 &
get_events '"jupiler_pro_league"' 1817

wait

cat *_pinnacle_league_events.csv >> raw_pinnacle_events.csv
rm *_pinnacle_league_events.csv

events=$(cat < raw_pinnacle_events.csv)

IFS=$'\n'
for event in ${events}
do
  home_team=$(echo "${event}" | cut -d',' -f 2)
  away_team=$(echo "${event}" | cut -d',' -f 3)
  home_team_id=$(get_participant_id "${home_team}")
  away_team_id=$(get_participant_id "${away_team}")
  sportradar_id=$(grep ''"${home_team_id}"'' sportradar_events.csv | grep ''"${away_team_id}"'' | cut -d',' -f 1)
  if [ -n "${sportradar_id}" ]
  then
  echo "${event}","${sportradar_id}" | awk -F"," -v OFS="," '{print $1,$6,$4,$5}' >> pinnacle_events.csv
  fi
done

rm raw_pinnacle_events.csv

echo GOT PINNACLE...





