#!/bin/bash

curl -s 'https://lsc.fn.sportradar.com/sportradar/en/Europe:Berlin/gismo/match_info/'$1 \
| jq --raw-output '.doc[0].data.match.result 
| [.home, .away, .home + .away, if (.winner == "home") then "1" elif (.winner == "away") then "2" else "X" end] 
| @csv' 