#!/bin/bash

# competition like MS (men's singles) or LS (ladies's singles)
wimbledon_draws(){
    year=$1
    curl 'https://www.wimbledon.com/en_GB/scores/feeds/'"${year}"'/draws/MS.json' > draws_"${year}"_MS.json
    curl 'https://www.wimbledon.com/en_GB/scores/feeds/'"${year}"'/draws/LS.json' > draws_"${year}"_LS.json
}

wimbledon_draws $1