#!/bin/bash

wimbledon_score() {
    year=$1
    day=$2
    output=$(curl 'https://www.wimbledon.com/en_GB/scores/feeds/'"${year}"'/completed_matches/days/day_'"${day}"'.json')
    echo "${output}"
}

wimbledon_score $1 $2