#!/bin/bash

readonly HOST=$1
readonly LISTEN_PORT=$2
readonly MESSAGE=$3

websocat -t -B 1000000 -E tcp-l:127.0.0.1:"${PORT}" reuse-raw:wss://"${HOST}" --max-messages-rev 1&
WS_PID=$!

#input
echo "${MESSAGE}" | nc 127.0.0.1 "${PORT}"

# output
success=$(nc 127.0.0.1 "${PORT}")

if [ -n "${success}" ]
then
  echo "${WS_PID}"
fi
