#!/bin/bash

sportradar_id=$1
kambi_id=$2
sbtech_id=$3
pinnacle_id=$4

echo About to get all betoffers...

./kambi "${kambi_id}" "${sportradar_id}" &
./sbtech "${sbtech_id}" "${sportradar_id}" &
./pinnacle "${pinnacle_id}" "${sportradar_id}"

wait

betoffers=$(cat *_betoffers.csv)

echo Found betoffers...

echo Look for value bets...

add_value_calculations(){
    bet_type=$1
    bet_option=$2
    bet_line=$3
    IFS=$'\n'
    for betoffer in "${betoffers}";do
        prediction=$(echo "${betoffer}" | grep -w "${bet_type}" | grep "pinnacle" | grep "${bet_option}" | grep "${bet_line}" | cut -d ',' -f 7)
        echo "${betoffer}" | grep -w "${bet_type}" | grep -v "pinnacle" | grep "${bet_option}" | grep "${bet_line}" \
        | while read -r offer ; do
            price=$(echo "${offer}" | cut -d ',' -f 5)
            value=$(./utils/calculate_value "${price}" "${prediction}")

        if (( $(echo "$value > 0" |bc -l) )); then
            echo "${offer}","${value}"
        fi 
        done
    done

}

add_value_calculations "1X2" '"1"' &
add_value_calculations "1X2" '"X"' &
add_value_calculations "1X2" '"2"' &
add_value_calculations "OVER_UNDER" '"Over"' ",2.5" &
add_value_calculations "OVER_UNDER" '"Under"' "2.5" 
wait

echo Value bets found...

#rm *betoffers.csv




