#!/bin/bash

betoffers=$(cat *_betoffers.csv)

IFS=$'\n'
for betoffer in "${betoffers}";do
prediction=$(echo "${betoffer}" | grep -w "1X2" | grep "pinnacle" | grep '"1"' | cut -d ',' -f 7)
offers=$(echo "${betoffer}" | grep -w "1X2" | grep -v "pinnacle" | grep '"1"')
    for offer in "${offers}";do
        lol=$(./utils/calculate_value $(echo "${offer}" | cut -d ',' -f 5) 1.23)
        echo "${lol}"
    done
done



