#!/bin/bash

sportradar_id=$1
kambi_id=$2
sbtech_id=$3
pinnacle_id=$4

echo About to get all betoffers...

./kambi "${kambi_id}" "${sportradar_id}" &
./sbtech "${sbtech_id}" "${sportradar_id}" &
./pinnacle "${pinnacle_id}" "${sportradar_id}"

wait



