#!/bin/bash

event_id=1374679436
sport_radar_id=$2


curl -s 'https://guest.api.arcadia.pinnacle.com/0.1/matchups/1374679436/markets/related/straight' \
  -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
  -H 'X-Device-UUID: 9585db37-f7c6740c-e3129e9b-c7724b36' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -H 'Referer: https://www.pinnacle.com/' \
  -H 'X-API-Key: CmX2KcMrXuFmNg6YFbmTxE0y9CIrOi0R' \
  --compressed \
  | jq -r --arg eventId "${event_id}" '.[] | .key as $type_id | .matchupId as $market_id | (.prices[] | [$market_id, $type_id, $eventId, "pinnacle", if (.designation) then .designation else .participantId end, .price, .points] | @csv)' > betoffers_pinnacle.csv

curl -s 'https://guest.api.arcadia.pinnacle.com/0.1/matchups/1374679436/related' \
  -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
  -H 'X-Device-UUID: 9585db37-f7c6740c-e3129e9b-c7724b36' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -H 'Referer: https://www.pinnacle.com/' \
  -H 'X-API-Key: CmX2KcMrXuFmNg6YFbmTxE0y9CIrOi0R' \
  --compressed \
    | jq -r '.[] | .parentId as $parent_id | .id as $id | .special.description as $description | (.participants[] | [$parent_id, $id, $description, .name, .order, .id] | @csv)' > markets_pinnacle.csv


grep "${event_id}", ./betoffers_pinnacle.csv | sed 's/"s;0;m"/"1X2"/g; s/"s;1;m"/"1X2_H1"/g;' > all_main_offers.csv
grep "1X2" all_main_offers.csv > main_offers.csv
grep -v "${event_id}", ./betoffers_pinnacle.csv > special_offers.csv



grep -w '"Double Chance"' markets_pinnacle.csv

