#!/bin/bash

sport_radar_matches=$2
golden_palace_league_ids=$1


get_events() {
    league_id=$1
    book='goldenpalace'
    curl -G -s 'https://sb2frontend-altenar2.biahosted.com/api/Sportsbook/GetEvents' \
    -d timezoneOffset=-120 \
    -d langId=8 \
    -d skinName="${book}" \
    -d configId=19 \
    -d culture=en-gb \
    -d countryCode=BE \
    -d deviceType=Desktop \
    -d numformat=en \
    -d integration="${book}" \
    -d sportids=0 \
    -d categoryids=0 \
    -d champids="${league_id}" \
    -d group=AllEvents \
    -d period=periodall \
    -d withLive=false \
    -d outrightDisplay=none \
    -d couponType=0 \
    -d startDate=2021-06-16T12%3A21%3A00.000Z \
    -d endDate=2030-06-23T12%3A21%3A00.000Z \
    | jq --raw-output '.Result.Items[0].Events | map(.ExtId |= split(":"))[] | [.Id, .ExtId[2], "golden_palace"] | @csv'
}

for league_id in $golden_palace_league_ids;do
  get_events "${league_id}" &
done

wait
