#!/bin/bash

sport_radar_matches=$2
ladbrokes_league_ids=$1

get_events() {
    league=$1
    curl -s 'https://www.ladbrokes.be/detail-service/sport-schedule/services/meeting/calcio/'"${league}"'?prematch=1&live=0' \
    --header 'x-eb-accept-language: en_BE' \
    --header 'x-eb-marketid: 5' \
    --header 'x-eb-platformid: 2' \
    | jq --raw-output '.result.dataGroupList[].itemList[].eventInfo | [.aliasUrl, .programBetradarInfo.matchId, "ladbrokes"] | @csv'
}

for league_id in $ladbrokes_league_ids;do
  get_events "${league_id}" &
done

wait