#!/bin/bash

sport_radar_matches=$2
meridian_league_ids=$1

get_events() {
  url=$1
  curl -s "${url}" | jq --raw-output '.[0].events[] | [.id, .betradarUnified["id"], "meridian"] | @csv'
}

for meridian_league_id in $meridian_league_ids;do
  get_events "${meridian_league_id}"
done