production:
  outputs:
    production:
      type: snowflake
      account: wb32444.eu-west-1
      user: pieterjandemuinck
      password: "{{ env_var('PASS') }}"
      role: SYSADMIN
      database: PRODUCTION
      warehouse: COMPUTE_WH
      schema: SCRAPERS
      threads: 3
  target: production