#!/bin/bash

# create persistent websocket client connection
# call nc 127.0.0.1:1234 to get messages

get_participant_id() {
  name=$1
  jq_string='.['"${name}"']'
  participant=$(cat < bcapps_sportradar.json | jq "${jq_string}")
  echo "${participant}"
}

echo GETTING BCAPPS

PORT=$1

websocat -t -B 1000000 -E tcp-l:127.0.0.1:"${PORT}" reuse-raw:wss://eu-swarm-ws-re.bcapps.net --max-messages-rev 1&
WS_PID=$!
echo created websocket client with pid "${WS_PID}"

rid=$(date +%s)

nc 127.0.0.1 "${PORT}"
echo about to log in...
echo '{"command":"request_session","params":{"language":"eng","site_id":"385","release_date":"15/09/2020-16:48"},"rid":"'"${rid}"'"}' \
| nc 127.0.0.1 "${PORT}"
nc 127.0.0.1 "${PORT}"

get_events() {
  local league_id=$1
  local league=$2
  echo '{"command":"get","params":{"source":"betting","what":{"game":["id", "team1_name", "team1_id", "team2_name", "team2_id"]},"where":{"competition":{"id":'"${league_id}"'}},"subscribe":true},"rid":"'"${rid}"'"}' \
  | nc 127.0.0.1 "${PORT}"

  nc 127.0.0.1 "${PORT}" | jq --raw-output '.data.data.game | values[] | [.id, .team1_name, .team2_name, "bcapps",'"${league}"'] | @csv'
}

get_events 538 '"premier_league"'
get_events 545 '"la_liga"'
get_events 541 '"bundesliga"'
get_events 543 '"serie_a"'
get_events 557 '"jupiler_pro_league"'
get_events 548 '"ligue_1"'

cat *_bcapps_league_events.csv >> raw_bcapps_events.csv
rm *_bcapps_league_events.csv

events=$(cat < raw_bcapps_events.csv)

IFS=$'\n'
for event in ${events}
do
  home_team=$(echo "${event}" | cut -d',' -f 2)
  away_team=$(echo "${event}" | cut -d',' -f 3)
  home_team_id=$(get_participant_id "${home_team}")
  away_team_id=$(get_participant_id "${away_team}")
  sportradar_id=$(grep ''"${home_team_id}"'' sportradar_events.csv | grep ''"${away_team_id}"'' | cut -d',' -f 1)
  if [ -n "${sportradar_id}" ]
  then
  echo "${event}","${sportradar_id}" | awk -F"," -v OFS="," '{print $1,$6,$4,$5}'
  fi
done

rm raw_bcapps_events.csv

echo kill websocket client...
kill -9 "${WS_PID}"

echo GOT BCAPPS

