#!/bin/bash

echo START GETTING Events

./meridian &
./altenar &
./cashpoint &
./bwin &
./kambi &
./betway &
./ladbrokes &
./sbtech &
./bingoal
#./zetbet &
#./betconstruct
wait 

echo event_id,sportradar_id,book,league,ds > events.csv
awk -v var="$(date +%Y-%m-%d)" -F"," 'BEGIN { OFS = "," } {$5=var; print}' *_events.csv >> events.csv
rm *_events.csv
sportradar_ids=$(mlr --csv --headerless-csv-output filter -S '$sportradar_id =~ "^[0-9]{8}$"' then uniq -g sportradar_id events.csv)

echo GET sportradar match info
for id in ${sportradar_ids}
do ../sportradar/match_info "${id}" | jq --raw-output '.doc[0].data.match | [._id, ._dt.date, ._dt.time, ._dt.tz, .teams.home._id, .teams.home.name, .teams.away._id, .teams.away.name] | @csv' > "${id}"_sportradar_match &
done

wait

echo sportradar_id,event_date,event_time,event_time_zone,home_id,home_name,away_id,away_name,ds > sportradar_events.csv
awk -v var="$(date +%Y-%m-%d)" -F"," 'BEGIN { OFS = "," } {$9=var; print}' *_sportradar_match >> sportradar_events.csv
rm *_sportradar_match
echo GOT sportradar match info

./pinnacle
awk -v var="$(date +%Y-%m-%d)" -F"," 'BEGIN { OFS = "," } {$5=var; print}' pinnacle_events.csv >> events.csv
rm pinnacle_events.csv

./betconstruct_apps 1589
awk -v var="$(date +%Y-%m-%d)" -F"," 'BEGIN { OFS = "," } {$5=var; print}' bcapps_events.csv >> events.csv
rm bcapps_events.csv

#aws s3 cp events.csv s3://bookmaker-events/ds=$(date +%Y-%m-%d)/soccer.csv --profile=default
#aws s3 cp sportradar_events.csv s3://sport-radar-events/ds=$(date +%Y-%m-%d)/soccer.csv --profile=default