#!/bin/bash

echo GETTING ZETBET...

get_events() {
  host=https://www.zebet.be/
  league=$1
  league_id=$2
  count=$3

  curl -s 'https://www.zebet.be/en/competition/'"${league_id}" \
    --compressed > "${league}"_zetbet.html

  events=$(grep 'href="/en/event/' "${league}"_zetbet.html | xargs)

  rm "${league}"_zetbet.html

  IFS='{' read -ra ADDR <<< "$events"
  for i in "${ADDR[@]}"; do
    count=$(( count + 1 ))
    if [[ "$i" == *href=* ]]; then
    event_id=$(echo "${i}" | cut -c 6-)
    curl -s $host$event_id > "${count}"_zetbet_events.html
    sportradar_id=$(grep 's5.sir.sportradar.com' "${count}"_zetbet_events.html | xargs | cut -d '/' -f 13 | cut -d ' ' -f 1)
    echo "${event_id}","${sportradar_id}","zetbet","${league}" >> "${league}"_zetbet_league_events.csv
    fi &
  done

  wait
}

get_events '"premier_league"' 94-premier_league 0 &
get_events '"jupiler_pro_league"' 101-pro_league_1a 100 &
get_events '"la_liga"' 306-primera_division 200 &
get_events '"bundesliga"' 268-bundesliga 300 &
get_events '"ligue_1"' 96-ligue_1_uber_eats 400 &
get_events '"serie_a"' 305-serie_a 500


wait

rm *_zetbet_events.html

cat *_zetbet_league_events.csv >> zetbet_events.csv
rm *_zetbet_league_events.csv

echo GOT ZETBET...






